# Generated by Django 6.1.1 on 2026-09-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_category_alter_color_options_product_delete_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
