# Generated by Django 6.1.1 on 2026-09-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_product_author'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_product_review',
        ),
    ]
