# Generated by Django 6.1.1 on 2026-09-13 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('code_hash', models.CharField(max_length=255, verbose_name='کد تایید هش شده')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'بازیابی رمز عبور',
                'verbose_name_plural': 'بازیابی\u200cهای رمز عبور',
            },
        ),
    ]
