# Generated by Django 6.1.1 on 2026-09-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_passwordresetverification'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='passwordresetverification',
            index=models.Index(fields=['phone'], name='accounts_ap_phone_dafc5e_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetverification',
            index=models.Index(fields=['expires_at'], name='accounts_ap_expires_1e08c6_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationverification',
            index=models.Index(fields=['phone'], name='accounts_ap_phone_cb83f5_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationverification',
            index=models.Index(fields=['expires_at'], name='accounts_ap_expires_e99e04_idx'),
        ),
    ]
